#!/usr/bin/env python3
"""Derive the rain lock from the one this machine has installed.

The pack does NOT publish a frozen LockView.qml. A cloned plugin falls behind on
every `omarchy update`, and the lock carries the PAM and fingerprint flows inside
it: an old copy is the last one you want. So this always starts from
$OMARCHY_PATH's LockView.qml and applies one minimal change: drop the blurred
wallpaper and put the rain in its place.

The other ~200 lines (password, fingerprint, BorderSurface, wake-on-input) come
from the installed Omarchy. The post-update.d hook calls back here after every
update, so Omarchy's fixes keep reaching the lock.

If the block to replace does not appear exactly once, this aborts and leaves the
native lock alone. A half-patched lock is a machine that will not unlock.
"""

import filecmp
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

# Loaded by path rather than by name: this file is also exec'd straight from a
# spec in the repo's verification snippet, where lib/ is not on sys.path.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from provider import PROVIDER  # noqa: E402

HOME = Path.home()
PLUGINS = HOME / ".config/omarchy/plugins"
OMARCHY = Path(os.environ.get("OMARCHY_PATH", "/usr/share/omarchy"))
SOURCE = OMARCHY / "shell/plugins/lock"
RAIN_FILES = tuple(PROVIDER["rainFiles"])
RAIN_QML = RAIN_FILES[0]
# The QML type the lock instantiates is the file's own name, the way QML always
# resolves a component from a file beside it.
RAIN_COMPONENT = RAIN_QML.removesuffix(".qml")
PLUGIN_ID = PROVIDER["plugin"]["id"]

REPLACEMENT = f"""    // The lock's background is the rain, not the blurred wallpaper.
    // loadBackground already meant "this view is really on screen" (root.locked,
    // or the preview from `omarchy-shell lock preview`), so it governs whether
    // the rain runs: locked it rains, and on unlock it stops.
    //
    // Put here by {PROVIDER["cli"]}. Do not edit this file by hand: it is derived
    // again from Omarchy's LockView.qml on every `omarchy update`.
    {RAIN_COMPONENT} {{
      anchors.fill: parent
      running: root.loadBackground
      // A new lock or preview starts with a new fall. The component remains
      // alive between lock sessions, so construction alone would resume an old
      // clock after opening the lid.
      onRunningChanged: if (running) restart()
    }}
"""


def die(message):
    print(f"derive-lock: {message}", file=sys.stderr)
    sys.exit(1)


def end_of_block(text, start):
    """Index just past the brace that closes the block starting at `start`."""
    depth = 0
    i = text.index("{", start)
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    die("unbalanced braces in LockView.qml")


def patch(text):
    images = [m for m in re.finditer(r"^[ \t]*Image\s*\{", text, re.M)
              if "id: wallpaper" in text[m.start():end_of_block(text, m.start())]]
    if len(images) != 1:
        die(
            f"expected exactly one `Image {{ id: wallpaper }}` in LockView.qml, found "
            f"{len(images)}. Omarchy's lock has changed: leaving it alone.\n"
            f"  Please open an issue at {PROVIDER['repoUrl']} "
            f"with your `omarchy version`."
        )

    start = images[0].start()
    end = end_of_block(text, start)

    # The MultiEffect that blurs that image sits right behind it and goes too.
    rest = text[end:]
    if re.match(r"\s*MultiEffect\s*\{", rest):
        end += end_of_block(rest, 0)
    else:
        print("derive-lock: note, no MultiEffect after the wallpaper; carrying on",
              file=sys.stderr)

    return text[:start] + REPLACEMENT + text[end:]


def is_ours(directory):
    """The one ownership rule, shared with the CLI and uninstall.sh."""
    manifest = directory / "manifest.json"
    if not manifest.is_file():
        return False
    try:
        data = json.loads(manifest.read_text())
    except ValueError:
        return False
    if data.get("omarchy", {}).get("clonedFrom") != "omarchy.lock":
        return False
    if data.get("omarchy", {}).get("derivedBy") == PROVIDER["cli"]:
        return True
    return (directory / RAIN_QML).is_file()


def existing_clone():
    """The lock clone to derive into: ours first, then any raw clone.

    clonedFrom is the discovery and is_ours the ownership verdict. A raw clone
    that this run just made has neither mark yet and still has to be found.
    Ours comes back first, so a foreign clone that sorts earlier cannot hide it
    and stop `lock on` with a refusal that is not true."""
    first_raw = (None, None)
    for directory in sorted(PLUGINS.glob("*.lock")):
        manifest = directory / "manifest.json"
        if not manifest.is_file():
            continue
        try:
            data = json.loads(manifest.read_text())
        except ValueError:
            continue
        if data.get("omarchy", {}).get("clonedFrom") != "omarchy.lock":
            continue
        if is_ours(directory):
            return directory, data["id"]
        if first_raw[0] is None:
            first_raw = (directory, data["id"])
    return first_raw


def rain_source():
    """Where the shader, its atlas and the QML that draws them come from."""
    candidates = [PLUGINS / PLUGIN_ID, Path(__file__).resolve().parent.parent]
    for candidate in candidates:
        if all((candidate / name).is_file() for name in RAIN_FILES):
            return candidate
    die(f"cannot find {RAIN_QML}; install the {PLUGIN_ID} plugin first")


def stage_clone(target, plugin_id, rain):
    """Build the clone in a staging directory and move it into place.

    Writing into the live folder was the seam this closes. Saving ANY file under
    ~/.config/omarchy/plugins/ wakes Omarchy's watcher -- an `inotifywait -m -r`
    on that directory (PluginRegistry.qml:636) -- so copying six files in fired
    six events, and `rm -rf` on the way out would fire one per file again. A
    dot-prefixed name is skipped by the scanner on purpose
    (localPluginIdForPath, PluginRegistry.qml:707), so everything below is
    invisible until the two renames at the end. install.sh stages its own
    plugins the same way; this is the lock catching up.

    It also removes an ordering hazard rather than tiptoeing around it. The rain
    files used to be copied in BEFORE LockView was patched, because a live
    reload landing in between showed a lock whose atlas was not there yet:

        QQuickImage at .../MatrixRain.qml[37:3]: Cannot open: .../glyphs.png

    Nothing here is live until it is complete, so no order can be wrong.
    """
    staging = target.parent / f".{plugin_id}.staging"
    retired = target.parent / f".{plugin_id}.retired"
    shutil.rmtree(staging, ignore_errors=True)
    shutil.rmtree(retired, ignore_errors=True)
    staging.mkdir(parents=True)

    # Always start from Omarchy's sources: that brings an old clone up to date
    # and stops the patch from being applied twice on top of itself.
    for source_file in SOURCE.iterdir():
        if source_file.name == "manifest.json":
            continue  # the clone's carries its own id and clonedFrom; keep it
        shutil.copy2(source_file, staging / source_file.name)

    # The clone's own manifest, plus a marker saying who rebuilds it. A backup
    # tool has no other way to tell a derived directory from a hand-made one,
    # and freezing a copy of this is precisely what the derivation exists to
    # avoid: the frozen copy stops receiving Omarchy's own lock-screen fixes.
    # omarchy-replicant reads omarchy.derivedBy and leaves the directory alone.
    manifest_data = json.loads((target / "manifest.json").read_text())
    manifest_data.setdefault("omarchy", {})["derivedBy"] = PROVIDER["cli"]
    (staging / "manifest.json").write_text(json.dumps(manifest_data, indent=2) + "\n")

    for name in RAIN_FILES:
        shutil.copy2(rain / name, staging / name)

    lock_view = staging / "LockView.qml"
    lock_view.write_text(patch(lock_view.read_text()))

    # Validated BEFORE it goes live, for the same reason install.sh does it: a
    # folder that fails validation must never be the one the shell picks up.
    # Missing validator is not a reason to abort a derive -- but a failing one
    # is, and the clone already in place stays exactly as it was.
    if shutil.which("omarchy-plugin-validate"):
        if subprocess.run(["omarchy-plugin-validate", str(staging)],
                          capture_output=True).returncode != 0:
            shutil.rmtree(staging, ignore_errors=True)
            die(f"the derived lock does not pass Omarchy's validation.\n"
                f"  Your current lock at {target} is untouched.")

    # Every doctor derives again, and the result is usually what is live
    # already. A swap then only reloads the lock plugin in the running shell,
    # so an identical result stays in staging and goes.
    if same_tree(staging, target):
        shutil.rmtree(staging, ignore_errors=True)
        return False

    # Two renames rather than `rm -rf target; mv staging target`: the delete
    # would be one watcher event per file, which is the burst being avoided.
    os.replace(target, retired)
    os.replace(staging, target)
    shutil.rmtree(retired, ignore_errors=True)
    return True


def same_tree(a, b):
    """Whether two folders hold the same files, byte for byte."""
    names = sorted(p.relative_to(a) for p in a.rglob("*"))
    if names != sorted(p.relative_to(b) for p in b.rglob("*")):
        return False
    return all(filecmp.cmp(a / name, b / name, shallow=False)
               for name in names if (a / name).is_file())


def enabled(plugin_id):
    """Whether the running shell has the plugin enabled. No answer means no."""
    try:
        listed = subprocess.run(["omarchy-plugin-list", "--json"], check=True,
                                capture_output=True, text=True).stdout
        return any(p.get("id") == plugin_id and p.get("enabled")
                   for p in json.loads(listed))
    except (OSError, subprocess.CalledProcessError, ValueError):
        return False


def main():
    if not (SOURCE / "LockView.qml").is_file():
        die(f"cannot find Omarchy's lock at {SOURCE}")

    rain = rain_source()
    target, plugin_id = existing_clone()

    created = target is None
    if created:
        # Same reasoning as derive-plymouth: a traceback here reads as a broken
        # pack. This one cannot lock anybody out -- no clone means Omarchy's own
        # lock is still the enabled one -- but say so plainly.
        try:
            subprocess.run(["omarchy-plugin-clone", "omarchy.lock"], check=True)
        except (OSError, subprocess.CalledProcessError) as failure:
            die(f"could not clone Omarchy's lock ({failure}).\n"
                f"  Your native lock is untouched and still enabled.")
        target, plugin_id = existing_clone()
        if target is None:
            die("the lock clone did not appear after creating it")
        print(f"Cloned Omarchy's lock as {plugin_id}")
    elif not is_ours(target):
        die(f"{target} is a lock clone of yours, not of this pack -- it "
            f"is not marked as derived by {PROVIDER['cli']} and carries "
            f"no {RAIN_QML}. Rename it or remove it yourself first; "
            f"deriving over it would patch your own lock.")

    try:
        changed = stage_clone(target, plugin_id, rain)
    except SystemExit:
        # A FIRST derive that cannot patch hands the lock straight back. Left in
        # place, the raw clone stays enabled with Omarchy's own disabled by the
        # clone -- an unpatched lock that `status` cannot tell apart from ours.
        # `plugin remove` re-enables omarchy.lock (cloneSourceRestores), which
        # is exactly the state this run started from.
        if created:
            subprocess.run(["omarchy-plugin-remove", plugin_id, "--yes"],
                           check=False, capture_output=True)
            if existing_clone()[0] is not None:
                subprocess.run(["omarchy-plugin-remove", plugin_id],
                               check=False, capture_output=True)
        raise

    # The same lock, already in charge: nothing to tell the shell. After
    # `omarchy refresh shell` the clone is on disk but not enabled, so the
    # enable below still runs then.
    if not created and not changed and enabled(plugin_id):
        return
    subprocess.run(["omarchy-shell", "shell", "rescanPlugins"],
                   check=False, capture_output=True)
    subprocess.run(["omarchy-plugin-enable", plugin_id], check=False, capture_output=True)
    print(f"Lock derived at {target} (from {SOURCE})")


if __name__ == "__main__":
    main()
